#ifndef MEASUREMENT_CONFIG_H
#define MEASUREMENT_CONFIG_H

#define MEASUREMENT_MEASURE_C
// #define MEASUREMENT_PAPI_C
#define MEASUREMENT_TIMELIB_C

// #define PRINT_MEASUREMENTS

#endif /* MEASUREMENT_CONFIG_H */